### ISSUE TITLE
Add options page

### ISSUE THREAD

**Issue by antonlukin** [antonlukin/sharing-image#1]
Add custom options to plugin page:
- [ ] choose font (open sans, roboto, etc)
- [ ] add custom font
- [ ] insert logo as image or text
- [ ] title and logo position
- [ ] font size

**Comment by Krishnacore** [comment]
Tell me, please, where can I find these settings? They are not on the plugins page.

**Comment by antonlukin** [comment]
@Krishnacore I just want to add them in the future. You can fork plugin and add these settings via source code here https://github.com/antonlukin/social-image/blob/master/src/classes/Generation.php#L59
