### ISSUE TITLE
[feature request] Use post thumbnail/featured image for generating

### ISSUE THREAD

**Issue by tobaco** [antonlukin/sharing-image#15]
Hi,

it would be great, if the plugin would use the post thumbnail/featured image not only for autogeneration but also for the manual generation on the post edit screen. Right now it generates an "empty" image (just background color) with text (if defined in sharing image template). This would be in particular handy, if the user changes the template to replace the auto generated image.

Thanks!

**Comment by antonlukin** [comment]
Hi there,
thanks for your interest in the plugin. 
I've already tried to implement this behavior, but there was a problem with Block editor events.
Will try to do it once again.

**Comment by tobaco** [comment]
Thanks!

I tried to workaround this by using the `sharing_image_sanitize_picker` filter and setting the attachment if it was empty. But I couldn't  get the current post/queried object to look for the post thumbnail (via `get_post_thumbnail_id()` function).

It could probably work, if this filter had the post id as third param or in the picker array.

**Comment by antonlukin** [comment]
I have not looked in detail yet, but it seems you should pay attention to the filter `sharing_image_update_post_meta`.
https://github.com/antonlukin/sharing-image/blob/6fc42ca68e6131dc7918278a0c49a943e5ff2f1d/classes/class-widget.php#L216

**Comment by wpmad** [comment]
Hi, is there any update on this feature request? Or could you possibly provide some example code on how to use the `sharing_image_update_post_meta` filter to add the generated image to the WordPress Media Library and assign to the post as a featured image/post thumbnail?

**Comment by tobaco** [comment]
@wpmad 

My request was not about using the shared image as featured image, but to use the already defined featured image of a post as image for generating the shared image. 

I did it this way:

```
/**
 * @param string $meta    Updated post meta.
 * @param string $post_id Post ID.
 */
function mf_update_post_meta_sharing_image( $meta, $post_id ) {
	// get featured image
	$featured_image = get_post_thumbnail_id($post_id);

	if($featured_image) {
		if(isset($meta) && isset($meta['fieldset'])){
				// loop all templates
				foreach ($meta['fieldset'] as $index => $template) {
					// assign featured image as attachment if no attachment defined
					if(!isset($template['attachment']) || !$template['attachment']){
						$meta['fieldset'][$index]['attachment'] = $featured_image;
					}
				}
		}
	}

	return $meta;
}

add_filter( 'sharing_image_update_post_meta', 'mf_update_post_meta_sharing_image', 10, 2 );
```

For your request, you could use `sharing_image_poster_src()`, `media_sideload_image()` (https://developer.wordpress.org/reference/functions/media_sideload_image/) and `set_post_thumbnail()`.

e.g. (untested)

```
$post_id = [post id]
$url = sharing_image_poster_src($post_id);
$desc  = "image description";
if($url){
	$image = media_sideload_image( $url, $post_id, $desc,'id' );
	set_post_thumbnail( $post_id, $image );
}
```

**Comment by be2clack** [comment]
Hello everyone, can you make a full-fledged plugin?

**Comment by antonlukin** [comment]
@be2clack Can you clarify your request, please? 
What feature do you need?

**Comment by antonlukin** [comment]
It seems version 3.0 should solve this problem.
