### ISSUE TITLE
[feature request] Exclude post types from auto generation

### ISSUE THREAD

**Issue by tobaco** [antonlukin/sharing-image#16]
With the latest update sharing images are als generated for posts which are added programmatically.
I have some posts in some custom post types which do not have a public url and need no sharing image.

It would be nice to have to possibility to exclude or include post types for the autogeneration. This could be a setting or a filter.

Thanks!

**Comment by antonlukin** [comment]
Great idea, I will do. Thanks!

**Comment by antonlukin** [comment]
Hi, @tobaco 
I've added this new filter [sharing_image_disable_autogeneration](https://wpset.org/sharing-image/hooks/#sharing_image_disable_autogeneration). You can disable autogeneration by post type:

```php
function my_disable_autogeneration( $disable, $post_id ) {
    if ( 'page' === get_post_type( $post_id ) ) {
        return true;
    }
}

add_filter( 'sharing_image_disable_autogeneration', 'my_disable_autogeneration', 10, 2 );
```

**Comment by tobaco** [comment]
Thank you! 🤩
