### ISSUE TITLE
Error while activatiing

### ISSUE THREAD

**Issue by Mayhopar** [antonlukin/sharing-image#3]
> Warning: require_once(…/plugins/social-image/vendor/composer/autoload_real.php): failed to open stream: No such file or directory in …/plugins/social-image/vendor/autoload-real.php on line 5
> 
> Fatal error: require_once(): Failed opening required '…/plugins/social-image/vendor/composer/autoload_real.php' (include_path='.:/usr/local/pear/php56') in …/plugins/social-image/vendor/autoload-real.php on line 5

**Comment by Krishnacore** [comment]
Hi! I have similar issue.

Warning: require_once(.../plugins/social-image/vendor/autoload.php): failed to open stream: No such file or directory in .../plugins/social-image/social-image.php on line 21 Fatal error: require_once(): Failed opening required '...t/plugins/social-image/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in .../plugins/social-image/social-image.php on line 21

**Comment by Krishnacore** [comment]
And i have solution!) Install composer in plugin directory
