### ISSUE TITLE
привет

### ISSUE THREAD

**Issue by be2clack** [antonlukin/sharing-image#5]
Можете обновить на последнюю версию wordpress? там не хватает vendor/autoload . в общем не устанавливается

**Comment by antonlukin** [comment]
Необходимо установить зависимости с помощью [composer](https://getcomposer.org/).
В папке с плагином ввести команду `composer install`.

Добавлю информацию в инструкцию по установке

**Comment by be2clack** [comment]
> Необходимо установить зависимости с помощью [composer](https://getcomposer.org/).
> В папке с плагином ввести команду `composer install`.
> 
> Добавлю информацию в инструкцию по установке

у меня хостинг на  jino / как быть?

**Comment by be2clack** [comment]
мне хостинг не дает права в ssh делать подобные команды, просто скачать и загрузить этот файл нельзя?

**Comment by antonlukin** [comment]
Добавил папку vendor в ветку hosted. 
Попробуйте скачать релиз https://github.com/antonlukin/social-image/releases и залить на хостинг.

Пожалуйста, имейте в виду, что плагин достаточно сырой и ограничен в настройках.
Шрифты генерации пока можно изменить только [фильтром](https://github.com/antonlukin/social-image/blob/master/src/classes/Generation.php#L98).
Фильтр можно добавить в functions.php темы.

**Comment by be2clack** [comment]
Привет, ты еще не сделал для полноценный плагин для WP?

**Comment by be2clack** [comment]
> Добавил папку vendor в ветку hosted.
> Попробуйте скачать релиз https://github.com/antonlukin/social-image/releases и залить на хостинг.
> 
> Пожалуйста, имейте в виду, что плагин достаточно сырой и ограничен в настройках.
> Шрифты генерации пока можно изменить только [фильтром](https://github.com/antonlukin/social-image/blob/master/src/classes/Generation.php#L98).
> Фильтр можно добавить в functions.php темы.

Привет, ты еще не сделал для полноценный плагин для WP?
