### ISSUE TITLE
Привет, когда доработаешь?

### ISSUE THREAD

**Issue by be2clack** [antonlukin/sharing-image#6]
Привет еще раз, поверь нигде нету аналога твоего плагина. Замучался

Мне в принципе нужно только одна функция, автопостинг или хотя бы переменная с документацией для интеграция обложки который сгенерировал через твой модуль чтоб можно было интегрировать в другие модули с автопостингом в соц сети

**Comment by antonlukin** [comment]
Постараюсь через месяц выложить плагин в каталог WordPress. 
Задачу закрываю, чтобы не мешала.

**Comment by be2clack** [comment]
Привет, как найти в каталоге?

**Comment by antonlukin** [comment]
Пока в разработке. Не раньше апреля выйдет. Скину ссылку в эту задачу

**Comment by antonlukin** [comment]
Готово
https://wordpress.org/plugins/sharing-image/
